### ISSUE TITLE
Adding Language WS maintainers to `owners`

### ISSUE THREAD

**Issue by quaid** [inclusivenaming/website#140]
We have a **lot** of work backed up in the Language WS that is website related:  terms to add or evolve, improvements to the website, and improvements to the word lists. And love and respect for the owners of the `inclusivenaming` org, but y'all don't have the time to come get the understanding for each PR that the Language WS has about these changes and be willing/able to approve them, change them, etc.

So .... let's deligaaaaaaaaaaate!

Would @edwarnicke get approved and/or do the changes to the `inclusivenaming` GitHub org and/or to just the `website` repo to allow some of us in the Language WS to approve PRs?

We discussed this in our meeting today and here is the list of people we'd like to add:

@LarryKunz
@quaid
@lex-joy 
@markcmiller86 < Mark wasn't in the meeting but I recall his interest in helping with GitHub, so I am boldly adding him

All the above folks have long-standing/since-the-beginning relationships to Inclusive Naming as contributors to the Language WS. If the Language WS had it's own repo (hint, hint), these would be some of the maintainers.

If there isn't granularity to give merge permissions to these folks for just the `website` repo, then can we either fix that or just keep skipping that and let these folks have permissions? This stuck-state has been unchanged for most of a year for the Language WS.

If there is a governance issue blocking these folks being made maintainers of the `website` repo, do we fix the governance or does the governance tell us what to do when existing maintainers aren't merging and active contributors want to? (And does the governance tell us why and how people get merge rights, in particular, people who are active in the project compared to inactive or new people?) Asking because the governance I find is [https://github.com/inclusivenaming/org/tree/main/governance](blank).

During discussions in the meeting today I realized that @abuango is actually a maintainer and could do merges, but ironically one of the key PRs we want to merge is the PR he opened! If he's not supposed to merge his own PR ...

**Comment by abuango** [comment]
Thank you very much @quaid for raising this issue. Deligation is truly necessary for moving things forward.

I checked the permissions of the `website` project, and I noticed you, @lex-joy & @LarryKunz are members of the `website-maintainers` team, which gives `maintain` permission to the website project. If any of you cannot utilize these permissions properly, we must look at the PR review policies. I know a PR requires at least one review to merge.

I will be inviting @markcmiller86 to the the `website-maintainers` team. As for my PR, I was waiting for the 1 review, so I could merge, but I have asked @taylorwaggoner to merge for me.
