### ISSUE TITLE
Sea Lions

### ISSUE THREAD

**Issue by LawrenceHecht** [inclusivenaming/website#68]
You are being overly harsh on people you call sea lions. Today's "sea lion" can be tomorrow's friend. In most cases they are trying to help. You can close this issue now. I just got upset when reading the "us" vs "them" mentality on the page.

With some irony,

Lawrence

**Comment by rbowen** [comment]
I agree with the "us vs them" comment here, and see it also in this statement on this page: https://inclusivenaming.org/language/implementation-path/

> We encourage you to take a stance of banning/blocking as quickly as possible.

It's critical that everyone keep front-of-mind at all times that this project is about compassion and making the world better, not about winning, scoring points, or driving metrics.

In both cases, I understand the reason for the remarks. Wow, do I ever. There are absolutely some bad players out there. But as soon as we divide up the world into us and them, we are in danger of becoming the very thing we are working against.

Always assume good intent.
