### ISSUE TITLE
SDDI doesn't exist

### ISSUE THREAD

**Issue by LawrenceHecht** [inclusivenaming/website#69]
You should get rid of the SDDI logo. The project doesn't exist. It was "created" and had a listserv for a few months (https://groups.linuxfoundation.org/g/sddi-formation) but is not longer active. @celestehorgan

**Comment by celestehorgan** [comment]
@LawrenceHecht I'll look into it, thanks!

**Comment by kestewart** [comment]
@LawrenceHecht - it exists.  Just bandwith issue to get the independent meetings happening.    Its all volunteer.

**Comment by LawrenceHecht** [comment]
I apologize. I should have just said the link didn't work. I found out why. It was pointing to the wrong URL. It should go to: https://sddiproject.org/ instead of https://sddi.org
