### ISSUE TITLE
Update Media header

### ISSUE THREAD

**Issue by xmulligan** [inclusivenaming/website#77]
Rather than having the blog in the top nav, it should be a drop down menu for all of our marketing related things. The top tab should be "News & Media" and the drop down should list "Blog, Media mentions, Branding, and Presentations" like on the CNCF homepage

![image](https://user-images.githubusercontent.com/29048870/119848217-edcb4800-bf0b-11eb-973d-32d0c3280ad0.png)

**Comment by xmulligan** [comment]
cc @celestehorgan

**Comment by gkarthiks** [comment]
If everyone agrees on the above proposal, I will create a PR with the changes.

**Comment by celestehorgan** [comment]
@gkarthiks please go ahead, I'll unassign myself.

**Comment by xmulligan** [comment]
@gkarthiks do you have any updates on this?

**Comment by gkarthiks** [comment]
hi, sorry @xmulligan. I haven't moved past 30% yet per se.

**Comment by gkarthiks** [comment]
@xmulligan is this how you want to see this? https://dazzling-wiles-0c8b21.netlify.app/

**Comment by xmulligan** [comment]
A good start, I would make the drop downs "Blog, Media mentions, Branding, and Presentations" rather than links to all of our socials though.

**Comment by gkarthiks** [comment]
got it. Will work on that.

**Comment by gkarthiks** [comment]
what do you expect to put inside the following?? 
* Branding
* Presentations

I assume all the links for social are to be a child for "Media mentions"? 

But doesn't seem to be odd to have the links of our social media rather than the mentions of INI?

**Comment by xmulligan** [comment]
Branding would be something similar to https://github.com/cncf/artwork, but maybe we skip that for now as we don't have it built out.

Presentations should link to https://github.com/inclusivenaming/org/tree/main/ws-marketing

Media mentions I would expect to be something similar to https://www.cncf.io/news/, not the social media

Does that make sense?

**Comment by gkarthiks** [comment]
yup! Thanks for the input. Will work on this.

**Comment by gkarthiks** [comment]
@xmulligan  can you check this out and let me know?? https://app.netlify.com/sites/dazzling-wiles-0c8b21/deploys/610879cf5607650007795f68?utm_source=github&utm_campaign=bot_dl

**Comment by xmulligan** [comment]
I think this is awesome! Looks good to me to merge

**Comment by gkarthiks** [comment]
cool, created the PR.

**Comment by xmulligan** [comment]
@gkarthiks thanks so much for the help on this!
