### ISSUE TITLE
Access to maintain the INI website

### ISSUE THREAD

**Issue by xmulligan** [inclusivenaming/website#80]
from @rbowen "At the risk of being annoying ... who's on deck for PRs to the website repo? There's a significant backlog, and it's going to lead to conflicts in a number of these, depending on what order they get addressed."

https://inclusive-naming.slack.com/archives/C01JCKTUS6M/p1622138367044900

## We should define who has access and the responsibility to merge and maintain the website

**Comment by gkarthiks** [comment]
FYI: I am up for it.

**Comment by celestehorgan** [comment]
IMO:
- Me 
- @xmulligan 
- @gkarthiks would be a wonderful addition to this crew! 

I'd love 1-2 more maintainers for the website, aside from this.

**Comment by rbowen** [comment]
Having some kind of +2 requirement (ie, two +1 reviews, not by the person who sent the PR) for merging could spread the load around and ensure that everything has adequate oversight.

**Comment by xmulligan** [comment]
@celestehorgan can you also add @Shahed-al since she is the marketing WS lead?
